### ISSUE TITLE
Un able to download any RHS mod

### ISSUE THREAD

**Issue by Dagaboo** [alec-hs/Flaxs-Arma-Server-Tool-2#54]
when dowloading some mods this will apear and i have no way on installing mods
 downloading item 861133494 ..
SteamCMD Exited

**Comment by alec-hs** [comment]
As Caladari mentioned, this is due to slow network not completing the mod download. Retry the download and after a few times the download will complete. I am working on auto retry for failed downloads.

This is a SteamCMD feature rather than a bug to prevent connections staying active for too long. Causes issues for big mods though.
