### ISSUE TITLE
Steam Auth Code Window Not Opening

### ISSUE THREAD

**Issue by diveyez** [alec-hs/Flaxs-Arma-Server-Tool-2#64]
When I launch the update features the window for steam authentication code does not show anymore. Nothing has changed and it has been stable for weeks until now.

**Comment by TeckHybrid** [comment]
Thought I was going crazy this evening, trying to figure out what was wrong. I can confirm I'm experiencing the same thing. I can manually login via SteamCMD, but if I try to update a mod or steam from within FAST, the 2FA window never pops.

**Comment by CALADARI** [comment]
same here 
![image](https://user-images.githubusercontent.com/45614593/53297929-c4b93a00-3860-11e9-82ad-b8b86bcb40cb.png)
and that's it, for first few time i thought it was a network issue so i keep fast running and when i check few hours later it just stopped working.
The steamCMD working fine since i could login manually as few posts below.

**Comment by alec-hs** [comment]
@CALADARI know issue, check here - [TEMP FIX](https://forums.bohemia.net/forums/topic/220433-fast2-arma-server-and-steam-workshop-tool/?do=findComment&comment=3338913)

**Comment by CALADARI** [comment]
@alec-hs  wilco,thx for reply :D

**Comment by alec-hs** [comment]
Closing as duplicate of #72
